name: sensor-monitor
include:
- /var/lib/arduino-app-cli/assets/0.9.0/compose/arduino/dbstorage_tsstore/brick_compose.yaml
services:
  main:
    image: ghcr.io/arduino/app-bricks/python-apps-base:0.9.0
    depends_on:
      dbstorage-influx:
        condition: service_healthy
    volumes:
    - type: bind
      source: /home/arduino/ArduinoApps/sensor-monitor
      target: /app
    - type: bind
      source: /var/run/arduino-router.sock
      target: /var/run/arduino-router.sock
    - type: bind
      source: /sys/class/leds/blue:user
      target: /sys/class/leds/blue:user
    - type: bind
      source: /sys/class/leds/green:user
      target: /sys/class/leds/green:user
    - type: bind
      source: /sys/class/leds/red:user
      target: /sys/class/leds/red:user
    - type: bind
      source: /sys/class/leds/blue:bt
      target: /sys/class/leds/blue:bt
    - type: bind
      source: /sys/class/leds/green:wlan
      target: /sys/class/leds/green:wlan
    - type: bind
      source: /sys/class/leds/red:panic
      target: /sys/class/leds/red:panic
    devices:
    - /dev/video0
    - /dev/video1
    - /dev/dri
    ports:
    - 7000:7000
    user: 1000:1000
    group_add:
    - 44
    - 29
    - 991
    - 20
    - 1001
    entrypoint: /run.sh
    extra_hosts:
    - msgpack-rpc-router:host-gateway
    labels:
      cc.arduino.app: "true"
      cc.arduino.app.main: "true"
      cc.arduino.app.path: /home/arduino/ArduinoApps/sensor-monitor
    environment:
      APP_HOME: /home/arduino/ArduinoApps/sensor-monitor
      BIND_ADDRESS: 127.0.0.1
      DB_PASSWORD: Arduino15
      DB_USERNAME: admin
      HOST_IP: 192.168.1.207
      INFLUXDB_ADMIN_TOKEN: 392edbf2-b8a2-481f-979d-3f188b2c05f0
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: 5m
